"""initial migration

Revision ID: 10959eb7facb
Revises: e836897f80e1
Create Date: 2016-10-24 22:44:06.158550

"""

# revision identifiers, used by Alembic.
revision = '10959eb7facb'
down_revision = 'e836897f80e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
