"""inital migration

Revision ID: e836897f80e1
Revises: 3fbd89813138
Create Date: 2016-10-23 11:35:08.526803

"""

# revision identifiers, used by Alembic.
revision = 'e836897f80e1'
down_revision = '3fbd89813138'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
